language: node_js
node_js:
  - "9"
sudo: enabled
services:
  - mongodb
before_install:
- cp .env.example .env
- echo arangodb3 arangodb/password password root | sudo debconf-set-selections  # set username 'root'
- echo arangodb3 arangodb/password_again password root | sudo debconf-set-selections  # set password 'root'
- chmod +x setup_arangodb.sh
- ./setup_arangodb.sh
- rm -rf ArangoDB-3.2.2.tar.gz
- cd ArangoDB-3.2.2 && touch .eslintignore && find . -name '*.js' >> .eslintignore && cd ..
- npm install -g truffle
- npm install -g ganache-cli
script:
  - npm run lint
  - npm test
  - npm start &>start.log &
  - sleep 20
  - jobs
  - kill %1
  - node isStartHealthy.js
  - ganache-cli &>geneche.log &
  - cd modules/blockchain_interface/ethereum && rm -rf build && truffle migrate --reset --compile-all
  - cd ../../../..
  - jobs
  - kill %1
after_script:
- kill -9 $(pgrep arangod)
- rm -f start.log
- rm -f ganache.log